HASS_BASE_URL = 'http://10.0.100.154:8123'
HASS_PASSWORD = None
HASS_MQTT_DISCOVERY_ENABLED = True
HASS_MQTT_DISCOVERY_PREFIX = 'homeassistant'
HASS_THERMOSTAT_ID = 'climate.test_generic_thermostat'

HASS_MQTT_STATE_STREAM_PREFIX = HASS_MQTT_DISCOVERY_PREFIX

MQTT_HOST = '10.0.100.154'
MQTT_PORT = 1883
MQTT_USER = None
MQTT_PASSWORD = None
MQTT_KEEPALIVE = 120  # seconds

HOSTNAME = 'test-thermostat-remote'

TEMPERATURE_UNIT = '°C'
SENSOR_SAMPLE_INTERVAL = 30

PIN_DHT = 16  # D0
PIN_I2C_SCL = 5  # D1
PIN_I2C_SDA = 4  # D2
PIN_BTN_1 = 0  # D3
PIN_BTN_2 = 14  # D5
PIN_BTN_3 = 12  # D6
PIN_BTN_4 = 13  # D7

DISP_I2C_ADDR = 60
BME280_I2C_ADDR = 118

LIGHT_SLEEP_ENABLED = False
