HASS_HOST = 'http://10.0.100.154'
HASS_PORT = 8123
HASS_PASSWORD = None
HASS_MQTT_DISCOVERY_ENABLED = True
HASS_MQTT_DISCOVERY_PREFIX = 'homeassistant'

MQTT_HOST = '10.0.100.154'
MQTT_PORT = 1883
MQTT_USER = None
MQTT_PASSWORD = None
MQTT_KEEPALIVE = 120  # seconds

HOSTNAME = 'test-thermostat-remote'

TEMPERATURE_UNIT = '°C'
